// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$0 from "./loaders/404loader.ts";
import * as $$$1 from "./loaders/errorloader.ts";
import * as $$$2 from "./loaders/slowquote.tsx";
import * as $$$3 from "./loaders/types.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/Coupon.tsx";
import * as $$$$$$2 from "./sections/Faq.tsx";
import * as $$$$$$3 from "./sections/Footer.tsx";
import * as $$$$$$4 from "./sections/Header.tsx";
import * as $$$$$$14 from "./sections/hero-1.tsx";
import * as $$$$$$15 from "./sections/hero-2.tsx";
import * as $$$$$$5 from "./sections/Hero.tsx";
import * as $$$$$$16 from "./sections/hero2.tsx";
import * as $$$$$$6 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$7 from "./sections/Logos.tsx";
import * as $$$$$$8 from "./sections/Lugar.tsx";
import * as $$$$$$9 from "./sections/ProductAd.tsx";
import * as $$$$$$10 from "./sections/Testimonials.tsx";
import * as $$$$$$11 from "./sections/Theme/Theme.tsx";
import * as $$$$$$12 from "./sections/TwoBanner.tsx";
import * as $$$$$$13 from "./sections/Utils/types.ts";

const manifest = {
  "loaders": {
    "site/loaders/404loader.ts": $$$0,
    "site/loaders/errorloader.ts": $$$1,
    "site/loaders/slowquote.tsx": $$$2,
    "site/loaders/types.ts": $$$3,
  },
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/Coupon.tsx": $$$$$$1,
    "site/sections/Faq.tsx": $$$$$$2,
    "site/sections/Footer.tsx": $$$$$$3,
    "site/sections/Header.tsx": $$$$$$4,
    "site/sections/hero-1.tsx": $$$$$$14,
    "site/sections/hero-2.tsx": $$$$$$15,
    "site/sections/Hero.tsx": $$$$$$5,
    "site/sections/hero2.tsx": $$$$$$16,
    "site/sections/ImageWithParagraph.tsx": $$$$$$6,
    "site/sections/Logos.tsx": $$$$$$7,
    "site/sections/Lugar.tsx": $$$$$$8,
    "site/sections/ProductAd.tsx": $$$$$$9,
    "site/sections/Testimonials.tsx": $$$$$$10,
    "site/sections/Theme/Theme.tsx": $$$$$$11,
    "site/sections/TwoBanner.tsx": $$$$$$12,
    "site/sections/Utils/types.ts": $$$$$$13,
  },
  "apps": {
    "site/apps/deco/vtex.ts": $$$$$$$$$$$0,
    "site/apps/decohub.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
